// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnrollRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub private_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnrollResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub certificate: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub ca_certificate: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ControlMessage {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub connector_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub private_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceAuthorizeRequest {
    #[prost(string, tag = "1")]
    pub tenant_slug: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code_challenge: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub code_challenge_method: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub redirect_uri: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceAuthorizeResponse {
    #[prost(string, tag = "1")]
    pub auth_url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceTokenRequest {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code_verifier: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceTokenResponse {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub refresh_token: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub expires_in: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceRefreshRequest {
    #[prost(string, tag = "1")]
    pub refresh_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceRefreshResponse {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub refresh_token: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub expires_in: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceRevokeRequest {
    #[prost(string, tag = "1")]
    pub refresh_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceRevokeResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceEnrollCertRequest {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub public_key_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub os: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub client_version: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub device_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub device_model: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub device_make: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub serial_number: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceEnrollCertResponse {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub spiffe_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub certificate_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub ca_cert_pem: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub expires_at: i64,
    #[prost(string, tag = "6")]
    pub access_token: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeviceViewRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceResourceProto {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub port_from: i32,
    #[prost(int32, tag = "7")]
    pub port_to: i32,
    #[prost(string, tag = "8")]
    pub alias: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub remote_network_id: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub remote_network_name: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub firewall_status: ::prost::alloc::string::String,
    #[prost(bool, tag = "13")]
    pub has_port_from: bool,
    #[prost(bool, tag = "14")]
    pub has_port_to: bool,
    #[prost(bool, tag = "15")]
    pub has_alias: bool,
    #[prost(string, tag = "16")]
    pub connector_tunnel_addr: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceUserProto {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub role: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceWorkspaceProto {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub slug: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub trust_domain: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceSummaryProto {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub certificate_issued: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceSessionProto {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub expires_at: i64,
    #[prost(int64, tag = "3")]
    pub access_token_expires_at_hint: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceViewResponse {
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<DeviceUserProto>,
    #[prost(message, optional, tag = "2")]
    pub workspace: ::core::option::Option<DeviceWorkspaceProto>,
    #[prost(message, optional, tag = "3")]
    pub device: ::core::option::Option<DeviceSummaryProto>,
    #[prost(message, optional, tag = "4")]
    pub session: ::core::option::Option<DeviceSessionProto>,
    #[prost(message, repeated, tag = "5")]
    pub resources: ::prost::alloc::vec::Vec<DeviceResourceProto>,
    #[prost(int64, tag = "6")]
    pub synced_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DevicePostureRequest {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub spiffe_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub os_type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub os_version: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub firewall_enabled: bool,
    #[prost(bool, tag = "7")]
    pub disk_encrypted: bool,
    #[prost(bool, tag = "8")]
    pub screen_lock_enabled: bool,
    #[prost(string, tag = "9")]
    pub client_version: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub collected_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DevicePostureResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod enrollment_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    #[derive(Debug, Clone)]
    pub struct EnrollmentServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> EnrollmentServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> EnrollmentServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            EnrollmentServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn enroll_connector(
            &mut self,
            request: impl tonic::IntoRequest<super::EnrollRequest>,
        ) -> std::result::Result<tonic::Response<super::EnrollResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/controller.v1.EnrollmentService/EnrollConnector",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "controller.v1.EnrollmentService",
                "EnrollConnector",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn enroll_tunneler(
            &mut self,
            request: impl tonic::IntoRequest<super::EnrollRequest>,
        ) -> std::result::Result<tonic::Response<super::EnrollResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/controller.v1.EnrollmentService/EnrollTunneler",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "controller.v1.EnrollmentService",
                "EnrollTunneler",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn renew(
            &mut self,
            request: impl tonic::IntoRequest<super::EnrollRequest>,
        ) -> std::result::Result<tonic::Response<super::EnrollResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/controller.v1.EnrollmentService/Renew");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("controller.v1.EnrollmentService", "Renew"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod control_plane_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    #[derive(Debug, Clone)]
    pub struct ControlPlaneClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> ControlPlaneClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ControlPlaneClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ControlPlaneClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn connect(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::ControlMessage>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ControlMessage>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/controller.v1.ControlPlane/Connect");
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("controller.v1.ControlPlane", "Connect"));
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod device_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    #[derive(Debug, Clone)]
    pub struct DeviceServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> DeviceServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> DeviceServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            DeviceServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Unauthenticated — PKCE OAuth flow
        pub async fn device_authorize(
            &mut self,
            request: impl tonic::IntoRequest<super::DeviceAuthorizeRequest>,
        ) -> std::result::Result<tonic::Response<super::DeviceAuthorizeResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/controller.v1.DeviceService/DeviceAuthorize",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "controller.v1.DeviceService",
                "DeviceAuthorize",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn device_token(
            &mut self,
            request: impl tonic::IntoRequest<super::DeviceTokenRequest>,
        ) -> std::result::Result<tonic::Response<super::DeviceTokenResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/controller.v1.DeviceService/DeviceToken");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "controller.v1.DeviceService",
                "DeviceToken",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn device_refresh(
            &mut self,
            request: impl tonic::IntoRequest<super::DeviceRefreshRequest>,
        ) -> std::result::Result<tonic::Response<super::DeviceRefreshResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/controller.v1.DeviceService/DeviceRefresh");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "controller.v1.DeviceService",
                "DeviceRefresh",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn device_revoke(
            &mut self,
            request: impl tonic::IntoRequest<super::DeviceRevokeRequest>,
        ) -> std::result::Result<tonic::Response<super::DeviceRevokeResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/controller.v1.DeviceService/DeviceRevoke");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "controller.v1.DeviceService",
                "DeviceRevoke",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// JWT authenticated
        pub async fn device_enroll_cert(
            &mut self,
            request: impl tonic::IntoRequest<super::DeviceEnrollCertRequest>,
        ) -> std::result::Result<tonic::Response<super::DeviceEnrollCertResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/controller.v1.DeviceService/DeviceEnrollCert",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "controller.v1.DeviceService",
                "DeviceEnrollCert",
            ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn device_me(
            &mut self,
            request: impl tonic::IntoRequest<super::DeviceViewRequest>,
        ) -> std::result::Result<tonic::Response<super::DeviceViewResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/controller.v1.DeviceService/DeviceMe");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("controller.v1.DeviceService", "DeviceMe"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn device_sync(
            &mut self,
            request: impl tonic::IntoRequest<super::DeviceViewRequest>,
        ) -> std::result::Result<tonic::Response<super::DeviceViewResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/controller.v1.DeviceService/DeviceSync");
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("controller.v1.DeviceService", "DeviceSync"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn device_report_posture(
            &mut self,
            request: impl tonic::IntoRequest<super::DevicePostureRequest>,
        ) -> std::result::Result<tonic::Response<super::DevicePostureResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/controller.v1.DeviceService/DeviceReportPosture",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "controller.v1.DeviceService",
                "DeviceReportPosture",
            ));
            self.inner.unary(req, path, codec).await
        }
    }
}
